name: "AI Release Notes Generator"
description: "Automatically generate release notes using OpenAI."
author: "Your Name"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  openai_api_key:
    description: "OpenAI API key"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
